# -*- coding: utf-8 -*-
"""AutoResearcher .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmBDQttzu5EFceSiXYkog6FSfBmbnHKl
"""

!pip install sentence-transformers faiss-cpu transformers torch numpy matplotlib networkx PyPDF2 beautifulsoup4 requests reportlab fpdf streamlit

import os
os.makedirs("modules", exist_ok=True)
os.makedirs("sample_papers", exist_ok=True)

from PyPDF2 import PdfReader
from sentence_transformers import SentenceTransformer
import faiss, numpy as np
from transformers import pipeline
import matplotlib.pyplot as plt
from collections import Counter
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

def read_pdf(path):
    text = []
    reader = PdfReader(path)
    for page in reader.pages:
        if page.extract_text():
            text.append(page.extract_text())
    return "\n".join(text)

def summarize_text(text):
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    if len(text.split()) < 60:
        return text
    out = summarizer(text[:2500], max_length=200, min_length=60, do_sample=False)
    return out[0]['summary_text']

def plot_keywords(text):
    words = [w.lower().strip('.,()[]:;"') for w in text.split() if len(w) > 4]
    common = Counter(words).most_common(15)
    labels, counts = zip(*common)
    plt.figure(figsize=(8,4))
    plt.bar(labels, counts)
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.savefig("keywords.png")
    plt.close()
    return "keywords.png"

def create_report(title, summary, chart):
    c = canvas.Canvas("AutoResearcher_Report.pdf", pagesize=A4)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 800, title)
    c.setFont("Helvetica", 10)
    textobject = c.beginText(50, 770)
    for line in summary.split('\n'):
        textobject.textLine(line)
    c.drawText(textobject)
    c.drawImage(chart, 50, 400, width=500, preserveAspectRatio=True)
    c.save()
    print("✅ Report saved as AutoResearcher_Report.pdf")

# === Run demo ===
pdfs = ["sample_papers/example1.pdf", "sample_papers/example2.pdf"]
texts = [read_pdf(p) for p in pdfs]
summaries = [summarize_text(t) for t in texts]
combined = " ".join(summaries)
chart = plot_keywords(combined)
create_report("AutoResearcher – Insight Report", "\n\n".join(summaries), chart)

!pip install nltk

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

def compare_papers(summaries, titles=None):
    if titles is None:
        titles = [f"Paper {i+1}" for i in range(len(summaries))]

    stop_words = stopwords.words('english')
    vectorizer = TfidfVectorizer(stop_words=stop_words)
    tfidf_matrix = vectorizer.fit_transform(summaries)

    sim_matrix = cosine_similarity(tfidf_matrix)
    df = pd.DataFrame(sim_matrix, columns=titles, index=titles)

    print("📊 Similarity Matrix (0–1 scale):")
    display(df)

    mean_sim = np.mean(sim_matrix[np.triu_indices(len(summaries), k=1)])
    print(f"\n🔍 Average Cross-Paper Similarity: {mean_sim:.2f}")

    if mean_sim < 0.3:
        insight = "Papers explore very different topics — useful for broad literature review."
    elif mean_sim < 0.7:
        insight = "Papers overlap moderately — possible to integrate insights for comparative study."
    else:
        insight = "Papers are highly similar — redundancy detected, focus on one key direction."

    return df, insight

summaries = [summarize_text(t) for t in texts]

comparison, insight = compare_papers(summaries, ["Paper 1", "Paper 2"])
print("\n💡 Comparison Insight:", insight)

from transformers import pipeline

def generate_insights(summaries, comparison_df):
    summarizer = pipeline("text2text-generation", model="facebook/bart-large-cnn")

    combined_text = ""
    for i, s in enumerate(summaries):
        combined_text += f"Paper {i+1}: {s}\n\n"

    combined_text += "\nComparison Observations:\n"
    combined_text += str(comparison_df)

    prompt = (
        "You are an academic researcher. Analyze the papers above and write: "
        "1. A short paragraph comparing methodologies and findings. "
        "2. A short paragraph identifying research gaps. "
        "3. A paragraph suggesting a new research direction that combines both papers' strengths."
    )

    input_text = prompt + "\n\n" + combined_text[:4000]
    result = summarizer(input_text, max_length=350, min_length=100, do_sample=False)

    insight_text = result[0]['generated_text']
    print("💡 AutoResearcher Insights:\n")
    print(insight_text)

    return insight_text

insight_text = generate_insights(summaries, comparison)

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

def generate_final_report(summaries, comparison_insight, insight_text, chart_path=None):
    pdf_path = "AutoResearcher_Final_Report.pdf"
    c = canvas.Canvas(pdf_path, pagesize=A4)

    width, height = A4
    y = height - inch

    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, y, "AutoResearcher – Insight Report")
    y -= 0.4 * inch

    # Section 1: Summaries
    c.setFont("Helvetica-Bold", 13)
    c.drawString(1 * inch, y, "1. Paper Summaries")
    y -= 0.3 * inch
    c.setFont("Helvetica", 10)
    for i, summary in enumerate(summaries):
        c.drawString(1 * inch, y, f"Paper {i+1}:")
        y -= 0.2 * inch
        for line in summary.split('\n'):
            c.drawString(1.2 * inch, y, line[:100])
            y -= 0.18 * inch
            if y < 1 * inch:
                c.showPage()
                y = height - inch
                c.setFont("Helvetica", 10)
        y -= 0.2 * inch

    # Section 2: Comparison Insight
    c.setFont("Helvetica-Bold", 13)
    c.drawString(1 * inch, y, "2. Cross-Paper Comparison")
    y -= 0.3 * inch
    c.setFont("Helvetica", 10)
    for line in comparison_insight.split('\n'):
        c.drawString(1 * inch, y, line[:100])
        y -= 0.18 * inch
        if y < 1 * inch:
            c.showPage()
            y = height - inch
            c.setFont("Helvetica", 10)

    # Section 3: Generated Insights
    c.setFont("Helvetica-Bold", 13)
    c.drawString(1 * inch, y, "3. Auto-Generated Research Insights")
    y -= 0.3 * inch
    c.setFont("Helvetica", 10)
    for line in insight_text.split('\n'):
        c.drawString(1 * inch, y, line[:100])
        y -= 0.18 * inch
        if y < 1 * inch:
            c.showPage()
            y = height - inch
            c.setFont("Helvetica", 10)

    # Section 4: Keywords Chart (optional)
    if chart_path:
        y -= 0.3 * inch
        c.setFont("Helvetica-Bold", 13)
        c.drawString(1 * inch, y, "4. Keyword Distribution")
        y -= 0.5 * inch
        try:
            c.drawImage(chart_path, 1 * inch, y - 3 * inch, width=5.5 * inch, height=3 * inch)
        except:
            c.drawString(1 * inch, y, "[Chart image could not be loaded]")

    c.save()
    print(f"✅ Final report generated: {pdf_path}")

insight_text = generate_insights(summaries, comparison)

generate_final_report(summaries, insight, insight_text, "keywords.png")

# --- Enhanced Pretty Report (adds layout & styling, keeps old version intact) ---

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

def generate_final_report_pretty(summaries, comparison_insight, insight_text, chart_path=None):
    pdf_path = "AutoResearcher_Final_Report_Styled.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=60, bottomMargin=50)
    styles = getSampleStyleSheet()
    Story = []

    # Header
    title_style = styles["Title"]
    Story.append(Paragraph("AutoResearcher – Insight Report", title_style))
    Story.append(Spacer(1, 12))

    date_str = datetime.now().strftime("%d %B %Y")
    Story.append(Paragraph(f"Generated on: {date_str}", styles["Normal"]))
    Story.append(Spacer(1, 20))

    # Section 1 – Paper Summaries
    Story.append(Paragraph("<b>1. Paper Summaries</b>", styles["Heading2"]))
    for i, summary in enumerate(summaries):
        Story.append(Spacer(1, 8))
        Story.append(Paragraph(f"<b>Paper {i+1}:</b> {summary}", styles["BodyText"]))
    Story.append(Spacer(1, 20))

    # Section 2 – Cross-Paper Comparison
    Story.append(Paragraph("<b>2. Cross-Paper Comparison</b>", styles["Heading2"]))
    Story.append(Spacer(1, 8))
    Story.append(Paragraph(comparison_insight, styles["BodyText"]))
    Story.append(Spacer(1, 20))

    # Small summary table
    data = [["Paper", "Word Count", "Key Points"]]
    for i, summary in enumerate(summaries):
        keypoints = " ".join(summary.split()[:8]) + "..."
        data.append([f"Paper {i+1}", len(summary.split()), keypoints])
    table = Table(data, colWidths=[70, 100, 300])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.darkblue),
        ("TEXTCOLOR", (0,0), (-1,0), colors.whitesmoke),
        ("ALIGN", (0,0), (-1,-1), "LEFT"),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("BOTTOMPADDING", (0,0), (-1,0), 6),
        ("BACKGROUND", (0,1), (-1,-1), colors.lightgrey),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey)
    ]))
    Story.append(table)
    Story.append(Spacer(1, 20))

    # Section 3 – AI-Generated Insights
    Story.append(Paragraph("<b>3. Auto-Generated Research Insights</b>", styles["Heading2"]))
    Story.append(Spacer(1, 8))
    Story.append(Paragraph(insight_text, styles["BodyText"]))
    Story.append(Spacer(1, 20))

    # Section 4 – Keyword Chart
    if chart_path:
        try:
            Story.append(Paragraph("<b>4. Keyword Distribution</b>", styles["Heading2"]))
            Story.append(Spacer(1, 10))
            img = Image(chart_path, width=400, height=200)
            Story.append(img)
        except:
            Story.append(Paragraph("[Chart could not be loaded]", styles["BodyText"]))

    doc.build(Story)
    print(f"✅ Styled report generated: {pdf_path}")

generate_final_report_pretty(summaries, insight, insight_text, "keywords.png")

def generate_future_research_ideas(summaries, insight):
    from transformers import pipeline
    generator = pipeline("text-generation", model="microsoft/phi-2")



    summaries_text = "\n\n".join(summaries) if isinstance(summaries, (list, tuple)) else str(summaries)

    prompt = (
        "Generate 3 creative, futuristic research directions based on the following papers. "
        "Each point should be 2–3 sentences long and practical.\n\n"
        f"Paper Summaries:\n{summaries_text}\n\n"
        f"Comparison Insight:\n{insight}\n\n"
        "Future Research Directions:\n"
    )

    output = generator(prompt, max_new_tokens=250, truncation=True)
    text = output[0]["generated_text"]

    # Extract after keyword
    if "Future Research Directions:" in text:
        text = text.split("Future Research Directions:")[-1]

    lines = [line.strip() for line in text.split("\n") if line.strip()]
    formatted = []
    for i, line in enumerate(lines[:3]):
        formatted.append(f"{i+1}. {line}")

    return "\n".join(formatted)

future_ideas = generate_future_research_ideas(summaries, insight)
print("\n🚀 Future Research Suggestions:\n", future_ideas)

generate_final_report_pretty(summaries, insight, insight_text, "keywords.png")